### ISSUE TITLE
Small broadening

### ISSUE THREAD

**Issue by cglosser** [cgMedia/rabi_paper#16]
> The 0.6meV inhomogeneous QD linewidth in the new Fig.7, above whichall collective effects disappear, is very small, there are no suchquantum dots in the world (as far as I know).

**Comment by piermaro** [comment]
Referee: The 0.6meV inhomogeneous QD linewidth in the new Fig.7, above whichall collective effects disappear, is very small, there are no suchquantum dots in the world (as far as I know).


Reply: The referee is correct that the inhomogeneous broadening of currently available quantum dots systems is too large for observing the long features patterns in Fig 7. Impurity bound excitons, which have a much smaller inhomogeneous broadening, could be better for observing these features. Also, the technology of quantum dots is rapidly evolving, and novel systems with smaller inhomogeneous broadening, or alternatively larger dipoles, could be soon available. In particular, graphene-based quantum dots could be good candidates. Finally, the approach we present in this paper is very general and appropriate also to describe molecular and atomic systems, where the effect of inhomogeneous broadening is not a limiting factor.

Changes in the paper:
1) At the end of IV C: 
We note that currently inhomogeneous broadening in quantum dots is typically larger than the values allowing for observing these patterns. Impurity-bound excitons, which have a much smaller inhomogeneous broadening, could be better candidates to observe these effects \cite . 
@article{thewalt1977details,
  title={Details of the structure of bound excitons and bound multiexciton complexes in Si},
  author={Thewalt, MLW},
  journal={Canadian Journal of Physics},
  volume={55},
  number={17},
  pages={1463--1480},
  year={1977},
  publisher={NRC Research Press}
}

2)  In the introduction, paragraph 2. Early solutions strategies....
",but cannot adequately desctive near field regimes" -> " , or describe near field effects assuming spatial homogeneity \cite"
@article{stroud1972superradiant,
  title={Superradiant effects in systems of two-level atoms},
  author={Stroud Jr, CR and Eberly, JH and Lama, WL and Mandel, L},
  journal={Physical Review A},
  volume={5},
  number={3},
  pages={1094},
  year={1972},
  publisher={APS}
}

3) In the acknoledgments: add: Finally, we thank Dr. P. Schwendimann for a critical reading of the manuscript.
