### ISSUE TITLE
Curiously short decoherence times

### ISSUE THREAD

**Issue by cglosser** [cgMedia/rabi_paper#3]
>T1 time 10ps. This is very short, I am only aware of similarly short lifetimes under very strong Purcell enhancement. Have the authors chosen this because of computational restrictions?

**Comment by cglosser** [comment]
I had originally thought 10ps was roughly correct for these dots. Carlo confirmed it's a very short timescale, but it's still far longer than any of the other characteristic times we have in the system so it shouldn't affect *much*. We chose this value primarily so we would definitely have decoherence effects available and a 10ps simulation is pushing the upper bound of our computational time (at least until AIM).

**Comment by cglosser** [comment]
"While decoherence times of order 10ps are relatively short for experimental systems, we believe they capture the salient effects of emission as they're still longer than any other timescale in the system. Indeed, simulations of more than 100ps require a prohibitively large amount of computational time, so we have chosen to reduce T1 and T2 for expediency."

**Comment by cglosser** [comment]
@piermaro Does this need an equivalent statement in the paper, or only in the reviewer reply?

**Comment by piermaro** [comment]
?I would add a short sentence also in the paper.

C


Carlo Piermarocchi
Professor of Physics
Department of Physics and Astronomy
Michigan State University
Biomedical Physical Sciences Bldg.
567 Wilson Road, Room 4263
East Lansing, MI 48824
Tel (517) 884-5631
Fax (517) 353 4500
email: piermaro@msu.edu
http://www.pa.msu.edu/~carlo
________________________________
